// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4WDYNrOYVmrcEKp6sNHB9tMkQKDkQ_h8',
    appId: '1:155372923614:web:cc4a5f9e2bc4dbebfa304f',
    messagingSenderId: '155372923614',
    projectId: 'lapak-bantul-436dc',
    authDomain: 'lapak-bantul-436dc.firebaseapp.com',
    storageBucket: 'lapak-bantul-436dc.firebasestorage.app',
    measurementId: 'G-MRZFZK54TT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxhUYoRc2GuIqyS_UJEC0QEqsZ0rWj4Ug',
    appId: '1:155372923614:android:f0ffc82a014501a4fa304f',
    messagingSenderId: '155372923614',
    projectId: 'lapak-bantul-436dc',
    storageBucket: 'lapak-bantul-436dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPpYUx2iPpvFF6JTMGgq4GrmRO_DYnbNE',
    appId: '1:155372923614:ios:0d01966be9b01124fa304f',
    messagingSenderId: '155372923614',
    projectId: 'lapak-bantul-436dc',
    storageBucket: 'lapak-bantul-436dc.firebasestorage.app',
    iosClientId: '155372923614-joo8fb75e02j3l9jjiir23265vm2o8qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.lapakBantul',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPpYUx2iPpvFF6JTMGgq4GrmRO_DYnbNE',
    appId: '1:155372923614:ios:0d01966be9b01124fa304f',
    messagingSenderId: '155372923614',
    projectId: 'lapak-bantul-436dc',
    storageBucket: 'lapak-bantul-436dc.firebasestorage.app',
    iosClientId: '155372923614-joo8fb75e02j3l9jjiir23265vm2o8qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.lapakBantul',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4WDYNrOYVmrcEKp6sNHB9tMkQKDkQ_h8',
    appId: '1:155372923614:web:9f8089ff679a439dfa304f',
    messagingSenderId: '155372923614',
    projectId: 'lapak-bantul-436dc',
    authDomain: 'lapak-bantul-436dc.firebaseapp.com',
    storageBucket: 'lapak-bantul-436dc.firebasestorage.app',
    measurementId: 'G-YD1M9E57NQ',
  );
}
